### PR TITLE
Don't assume tap-ctl list will show minor number

### PR DESCRIPTION
**Pull request by jjd27**

### CODE REVIEW

**Comment by djs55** [comment]
Does this happen when a tapdisk has spawned but not been attached to a minor?

**Comment by franciozzy** [comment]
Yes. It can also happen in other cases such as device tear down.

**Comment by djs55** [comment]
In that case, I approve of this patch :)

**Comment by jjd27** [comment]
For the record:

# tap-ctl list
# tap-ctl spawn
tapdisk spawned with pid 16453
# tap-ctl allocate
/dev/xen/blktap-2/tapdev0
# tap-ctl list | cat
pid=16453
# tap-ctl attach -m 0 -p 16453
# tap-ctl list | cat
pid=16453 minor=0 state=0

**Pull request merged**
